services:
  catalogue:
    build: ./catalogue
    image: charandasa/catalogue:1.0.0
    container_name: catalogue
    depends_on:
    - mongodb
  user:
    build: ./user
    image: charandasa/user:1.0.0
    container_name: user
    depends_on:
    - mongodb
    - redis
  cart:
    build: ./cart
    image: charandasa/cart:1.0.0
    container_name: cart
    depends_on:
    - redis
  shipping:
    build: ./shipping
    image: charandasa/shipping:1.0.0
    container_name: shipping
    depends_on:
    - mysql
    - cart
  frontend:
    build: ./frontend
    image: charandasa/frontend:1.0.0
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
    - catalogue
    - user
    - cart

  redis:
    image: redis:7.0
    container_name: redis
  mysql:
    build: ./mysql
    image: charandasa/mysq;:1.0.0
    container_name: mysql

  mongodb:
    build: ./mongodb
    image: charandasa/mongodb:1.0.0
    container_name: mongodb

networks:
  default: 
    driver: bridge
    name: roboshop
    external: false